#!/usr/bin/env python3
"""The recording script, for a person rather than a model.

docs/VOICE.md asks for real readings, and what is in the repository today is
a text-to-speech placeholder. This writes out what somebody would actually
need in a booth: every line one character says, in one language, in the order
the chapter plays them, with the filename each take has to land on and a note
on who they are and who they are talking to.

    python3 tools/audio/export_script.py ru                 # every voiced part
    python3 tools/audio/export_script.py zh_CN --speaker SPEAKER_ELIAN
    python3 tools/audio/export_script.py en -o /tmp/script.md

Mandarin is the one that needs this most: Piper ships exactly one
clean-licensed zh_CN voice, so every Chinese character in chapter I is that
same voice pitched differently (docs/VOICE.md).

Nothing here reads the cast file's licence rules — this is for humans, and a
human's recording is theirs to license. CC BY 4.0 keeps it in this repo.
"""
import argparse, csv, glob, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CAST = os.path.join(ROOT, "tools", "audio", "voice_cast.json")
STRINGS = os.path.join(ROOT, "localization", "strings.csv")
DIALOGUES = os.path.join(ROOT, "data", "dialogues")
LOCALES = ["en", "ru", "uk", "zh_CN"]
LOCALE_NAMES = {"en": "English", "ru": "Русский", "uk": "Українська", "zh_CN": "简体中文"}

## Roughly the order chapter I plays them (docs/CHAPTER1.md), so a session
## follows the story instead of jumping around it. Anything not listed here
## is appended in file order.
DIALOGUE_ORDER = [
    "ch1_prologue", "ch1_prologue_short", "ch1_intro",
    "ch1_stranger", "npc_severin", "npc_nun", "npc_mara", "npc_villager",
    "voice_catacombs", "ch1_preacher", "npc_matthew", "npc_knight",
    "ch1_ophanim", "ch1_cutscenes", "ch1_notes",
]


def strings():
    out = {}
    with open(STRINGS, encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            key = (row.get("keys") or "").strip()
            if key:
                out[key] = {loc: (row.get(loc) or "").strip() for loc in LOCALES}
    return out


def lines_by_speaker():
    """speaker -> [(dialogue file, key)], in play order, no duplicates."""
    files = {}
    for path in sorted(glob.glob(os.path.join(DIALOGUES, "*.json"))):
        files[os.path.basename(path)[:-5]] = json.load(open(path, encoding="utf-8"))
    ordered = [name for name in DIALOGUE_ORDER if name in files]
    ordered += [name for name in sorted(files) if name not in DIALOGUE_ORDER]

    out, seen = {}, set()
    for name in ordered:
        doc = files[name]
        for dialogue in (doc if isinstance(doc, list) else [doc]):
            for node in dialogue.get("nodes", {}).values():
                speaker, text = node.get("speaker"), node.get("text")
                if speaker and text and (speaker, text) not in seen:
                    seen.add((speaker, text))
                    out.setdefault(speaker, []).append((name, text))
    return out


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("locale", choices=LOCALES, help="the language to record")
    parser.add_argument("--speaker", action="append", help="only this speaker id (repeatable)")
    parser.add_argument("-o", "--out", help="write here instead of stdout")
    args = parser.parse_args()

    cast = {k: v for k, v in json.load(open(CAST, encoding="utf-8")).items()
            if not k.startswith("_")}
    text_of = strings()
    by_speaker = lines_by_speaker()
    wanted = args.speaker or [s for s in cast if s in by_speaker]
    unknown = [s for s in wanted if s not in by_speaker]
    if unknown:
        sys.exit("no dialogue uses " + ", ".join(unknown))

    name_of = {s: text_of.get(s, {}).get(args.locale) or s for s in wanted}
    total = sum(len(by_speaker[s]) for s in wanted)

    md = []
    md.append("# Recording script — %s\n" % LOCALE_NAMES[args.locale])
    md.append("%d lines, %d parts. Generated by `tools/audio/export_script.py`; "
              "regenerate rather than editing this file.\n" % (total, len(wanted)))
    md.append("**How to deliver.** One file per line, mono, 22 kHz or better, "
              "no music or room tone. Name each file after its key and drop it in "
              "`assets/audio/voice/%s/` — a real recording simply replaces the "
              "generated one, nothing else changes. Then add yourself to "
              "`assets/CREDITS.md` and remove your character from "
              "`tools/audio/voice_cast.json`, or the next generator run will "
              "overwrite you. Full instructions: `docs/VOICE.md`.\n" % args.locale)

    for speaker in wanted:
        role = cast.get(speaker, {})
        md.append("\n## %s  <sub>`%s`</sub>\n" % (name_of[speaker], speaker))
        note = role.get("_note")
        if note:
            md.append("> %s\n" % note)
        md.append("\n| # | File | Line |")
        md.append("|---|---|---|")
        for index, (dialogue, key) in enumerate(by_speaker[speaker], 1):
            line = text_of.get(key, {}).get(args.locale, "").replace("|", "\\|")
            md.append("| %d | `%s.mp3` <sub>%s</sub> | %s |" % (index, key, dialogue, line))
        md.append("")

    text = "\n".join(md)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as handle:
            handle.write(text)
        print("%d lines for %d parts written to %s" % (total, len(wanted), args.out))
    else:
        print(text)


if __name__ == "__main__":
    main()
