#!/usr/bin/env python3
"""Fetches the music library described in music_manifest.json and turns it into
game-ready loops.

    python3 tools/audio/fetch_music.py            # everything missing
    python3 tools/audio/fetch_music.py --force    # re-encode everything

Every track is a free, attribution-compatible source (CC0, CC BY, OGA-BY): the
manifest is the credit list, and this script writes the rows of
assets/CREDITS.md from it so the two never drift apart.

Processing (needs ffmpeg): download to a cache, trim to MAX_SECONDS with a fade
in and out, normalise to -18 LUFS like the rest of the library (Audio.MUSIC_DB
then stays at 0 for these), encode MP3 (lame VBR q6). Playlists in
data/music/playlists.json are regenerated from the "playlists" field, so a room
that asks for "graveyard" gets one of several tracks at random.
"""
import json, os, subprocess, sys, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MANIFEST = os.path.join(ROOT, "tools", "audio", "music_manifest.json")
OUT_DIR = os.path.join(ROOT, "assets", "audio", "music")
CACHE = os.path.join(os.environ.get("MUSIC_CACHE", os.path.expanduser("~/.cache/ashes-of-eden/music")))
PLAYLISTS = os.path.join(ROOT, "data", "music", "playlists.json")
CREDITS = os.path.join(ROOT, "assets", "CREDITS.md")
MAX_SECONDS = 150
FADE = 2.5
QUALITY = "7"  # libmp3lame VBR: ~110 kbps, fine for loops under a mix (this ffmpeg has no libvorbis; Godot plays MP3 natively)
## Tracks that already live in the repository, kept as the first entry of their playlist.
EXISTING = {
    "menu": ["menu"], "village_night": ["village_night"], "graveyard": ["graveyard"], "dead_bridge": ["dead_bridge"],
    "boss_knight": ["boss_knight"], "boss_ophanim": ["boss_ophanim"], "arena": ["arena"], "end": ["end"],
}


def fetch(track):
    os.makedirs(CACHE, exist_ok=True)
    target = os.path.join(CACHE, track["slug"] + os.path.splitext(track["url"].split("?")[0])[1] or ".mp3")
    if os.path.exists(target) and os.path.getsize(target) > 1000:
        return target
    print("  downloading", track["title"])
    req = urllib.request.Request(track["url"], headers={"User-Agent": "ashes-of-eden/0.1 (music fetch; see tools/audio/fetch_music.py)"})
    with urllib.request.urlopen(req, timeout=120) as r, open(target, "wb") as f:
        f.write(r.read())
    return target


def encode(src, dst):
    duration = float(subprocess.check_output(["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", src]).decode().strip() or 0)
    length = min(duration, MAX_SECONDS)
    filters = f"atrim=0:{length:.2f},afade=t=in:st=0:d={FADE},afade=t=out:st={max(0.0, length - FADE):.2f}:d={FADE},loudnorm=I=-18:TP=-1.5:LRA=11"
    subprocess.check_call(["ffmpeg", "-y", "-v", "error", "-i", src, "-vn", "-af", filters, "-ar", "44100", "-ac", "2", "-c:a", "libmp3lame", "-q:a", QUALITY, dst])


def main():
    force = "--force" in sys.argv
    manifest = json.load(open(MANIFEST))
    playlists = {k: list(v) for k, v in EXISTING.items()}
    rows = []
    for track in manifest["tracks"]:
        dst = os.path.join(OUT_DIR, track["slug"] + ".mp3")
        if force or not os.path.exists(dst):
            try:
                encode(fetch(track), dst)
            except Exception as error:  # a dead link must not stop the rest of the library
                print("  FAILED", track["slug"], error)
                continue
        for name in track["playlists"]:
            playlists.setdefault(name, []).append(track["slug"])
        rows.append(f'| `audio/music/{track["slug"]}.mp3` | {track["author"]} — "{track["title"]}" | {track["page"]} | {track["license"]} — trimmed to {MAX_SECONDS}s, loudness-normalised, MP3 VBR q{QUALITY} by `tools/audio/fetch_music.py` |')
    os.makedirs(os.path.dirname(PLAYLISTS), exist_ok=True)
    json.dump({"_comment": "generated by tools/audio/fetch_music.py; a room's `music` name is looked up here first", "playlists": playlists}, open(PLAYLISTS, "w"), indent=2)
    credits = open(CREDITS).read()
    start, end = "<!-- music-manifest:start -->", "<!-- music-manifest:end -->"
    block = start + "\n" + "\n".join(rows) + "\n" + end
    if start in credits:
        credits = credits[:credits.index(start)] + block + credits[credits.index(end) + len(end):]
    else:
        credits = credits.rstrip("\n") + "\n\n### Music library (generated)\n\n| File | Author — title | Source | License / notes |\n|---|---|---|---|\n" + block + "\n"
    open(CREDITS, "w").write(credits)
    print(f"{len(rows)} tracks in {len(playlists)} playlists")


if __name__ == "__main__":
    main()
